import "../globals.css";

import { RemeetFullLogo } from "@/components/util/RemeetFullLogo";
import { RemeetIcon } from "@/components/util/RemeetIcon";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header className="border-b border-gray-200">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex flex-row gap-4 items-center ">
                <RemeetIcon size={50} />
                <RemeetFullLogo className="text-orange-500" fill="#fff" />
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
